Enh CI workflow: add first test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,24 +1,62 @@
-name: Build
+name: Build and test
 on:
   pull_request:
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+    env:
+      FORCE_COLOR: 1
+    # The matrix defines the runners and Python versions dynamically
+    strategy: # If one job fails, GitHub will still finish the rest of the matrix
+      fail-fast: false
+      matrix:
+        os:
+          # - ubuntu-latest  TODO
+          - windows-latest
+        python-version:
+          - "3.10"
+          # - "3.12"  TODO
 #    permissions:
 #      contents: write
     steps:
+    - name: Install VLC via Winget
+      if: matrix.os == 'windows-latest'
+      run: |
+        winget install VideoLAN.VLC --silent --accept-source-agreements --accept-package-agreements
     - uses: actions/checkout@v4
       with:
         fetch-depth: '0'
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v5
+      with:
+        python-version: ${{ matrix.python-version }}
+        cache: 'pip' # Automatically caches your packages to speed up builds
     - name: Prepare build
-      run: |
-        pip install build
+      run: pip install build
     - name: Build wheel
+      shell: bash
       run: |
         rm -rf dist
         python -m build -w -o dist .
-    - name: Result
+    - name: Build Result
+      shell: bash
       run: |
         ls -lth ./dist
-        unzip -l ./dist/*.whl
-  
+        unzip -l ./dist/*.whl || true
+    - name: Install as editable
+      shell: bash
+      run: |
+        # pip install $(ls ./dist/*.whl)[test]
+        pip install -e .[test]
+    - name: Install Result
+      run: |
+        pip list
+#    - name: Fix python-vlc
+#      run: pip install -U "python-vlc<3.1"
+    - name: Execute tests
+      shell: bash
+      run: |
+        pytest -v ./tests
